version: '3'
services: 
  app:
    container_name: todo-be
    restart: always
    build: .
    command: npm start
    ports: 
      - 7000:8080
    volumes: 
      - ./:/app
      - /app/node_modules 
    